include:
  - ./notebooks-backend/compose.yml
  - ./notes-backend/compose.yml
services:
  reverse-proxy:
    image: nginx:1.27.0
    volumes:
      - type: bind
        source: ./reverse-proxy/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - notes-app-net
    depends_on:
      - notebooks 
      - notes

networks:
  notes-app-net: